canton.features.enable-testing-commands = yes

canton {
  sequencers {
    sequencer1 {
      storage.type = memory
      public-api {
        address = 0.0.0.0
        port = 5018
      }
      admin-api {
        address = 0.0.0.0
        port = 5019
      }
      monitoring {
        http-health-server {
          address = 0.0.0.0
          port = 5090
        }
      }
    }
  }
  mediators {
    mediator1 {
      storage.type = memory
      admin-api.port = 5020
    }
  }
}

