canton.features.enable-testing-commands = yes

canton {
  participants {
    participant1 {
      storage.type = memory
      admin-api.port = 5001
      ledger-api {
        address = 0.0.0.0
        port = 5002
      }
    }
    participant2 {
      storage.type = memory
      admin-api.port = 5011
      ledger-api.port = 5012
    }
  }
  domains {
    localdomain {
      storage.type = memory
      public-api.port = 5018
      admin-api.port = 5019
    }
  }
}