canton.features.enable-testing-commands = yes

canton {
  participants {
    participant1 {
      storage.type = memory
      admin-api {
        # Permitir conexões de fora do host local
        address = 0.0.0.0
        port = 5001
        # Aumentando para 30MB
        max-inbound-message-size = 31457280
      }
      ledger-api {
        # Permitir conexões de fora do host local
        address = 0.0.0.0
        port = 5002
        # Aumentando para 30MB
        max-inbound-message-size = 31457280
      }
      http-ledger-api {
        # Permitir conexões de fora do host local
        address = 0.0.0.0
        port = 5003
      }
      monitoring {
        http-health-server {
          address = 0.0.0.0
          port = 5090
        }
      }
    }
  }
}

canton.monitoring.metrics {
  reporters = [{
    address = 0.0.0.0
    type = prometheus
    port = 5050
  }]
}
